// JSON database of all instruments and acceptable attribute value getRanges
// TODO: move to database?

let instruments = ['loop', 'stretch', 'play1', 'play2', 'audioin', 'noise', 'dab', 'varsaw', 'lazer', 'growl', 'bass', 'dirt', 'crunch', 'rave', 'scatter', 'charm', 'bell', 'gong', 'soprano', 'dub', 'viola', 'scratch', 'klank', 'feel', 'glass', 'soft', 'quin', 'pluck', 'spark', 'blip', 'ripple', 'creep', 'orient', 'zap', 'marimba', 'fuzz', 'bug', 'pulse', 'saw', 'snick', 'twang', 'karp', 'arpy', 'nylon', 'donk', 'squish', 'swell', 'razz', 'sitar', 'star', 'jbass', 'sawbass', 'prophet', 'pads', 'pasha', 'ambi', 'space', 'keys', 'dbass', 'sinepad'];
let attributes =  {
  'degree':[-16,16,'int'],
  'oct':[0,8,'int'],
  'dur':[0,64,'float'],
  'delay': [0,8,'float'],
  'blur':[0,64,'float'],
  'amplify':[0,1,'float'],
  'scale':[0,0,'string'],
  'bpm':[0,300,'int'],
  'sample':[0,16,'int'],
  'sus':[0,64,'float'],
  'fmod':[0,64,'float'],
  'pan':[-1,1,'float'],
  'amp':[0.01,1,'float'],
  'midinote':[0,127,'int'],
  'vib':[0,32,'float'],
  'vibdepth':[0, 1, 'float'],
  'slide':[-4,4,'float'],
  'slidedelay':[0,1,'float'],
  'slidefrom':[-4,4,'float'],
  'glide':[-12,12,'int'],
  'glidedelay':[0,1,'float'],
  'bend':[-4,4,'float'],
  'benddelay':[0,1,'float'],
  'coarse':[0,64,'int'],
  'pshift':[-24,24,'int'],
  'hpf':[0,16000,'float'],
  'hpr':[0,1,'float'],
  'lpf':[0,16000,'float'],
  'lpr':[0,1,'float'],
  'bpf':[0,16000,'float'],
  'bpr':[0,1,'float'],
  'bpnoise':[0,20000, 'float'],
  'chop':[0,64,'int'],
  'striate':[0,500,'int'],
  'tremolo':[0,64,'float'],
  'echo':[0,64,'float'],
  'echotime':[0,8,'int'],
  'spin':[0,32,'int'],
  'cut':[0,1,'float'],
  'room':[0,1,'float'],
  'mix':[0,1,'float'],
  'formant':[1,7,'float'],
  'shape':[0,1,'float'],
  'drive':[0,1,'float'],
  'dist':[0,1, 'float'],
  'crush':[0,32,'int'],
  'bits':[0,8,'int']
}
// TODO : 'freq', , 'buf', 'env','rate', 'channel','striate','rate', 'swell','beat_dur',

module.exports = {instruments: instruments, attributes: attributes}
